# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secib < Formula
  desc "CLI for the NPL SECIB gateway + MCP companion"
  homepage "https://github.com/Karugency97/secib-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_darwin_amd64.tar.gz"
      sha256 "c224f6aed2ae57738a6ba1a9aa2279b7a01370918ed3820132448cc92717aa05"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_darwin_arm64.tar.gz"
      sha256 "e2f8a7d97bc2529753fbca2045045d518d6be8cb4aeb6044ab787b4525cf779e"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_linux_amd64.tar.gz"
      sha256 "f23c604e1ff56f4f092d68453025793e1685b9f37de70bd8455f1c3fadeb56e6"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_linux_arm64.tar.gz"
      sha256 "1b7b569ba5e001bd84468aa3d73009d591a1545201f8a8c48688ff4b47857662"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  test do
    system "#{bin}/secib", "version"
  end
end
