# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secib < Formula
  desc "CLI for the NPL SECIB gateway + MCP companion"
  homepage "https://github.com/Karugency97/secib-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.2/secib_0.0.2_darwin_amd64.tar.gz"
      sha256 "ba3d5b6f24af9ae3a50a5311f35383b94c23a5cd4f254b9cbba39d817631f883"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.2/secib_0.0.2_darwin_arm64.tar.gz"
      sha256 "50910900b11259b32c1cf71aeaaa11fae43903252db32e4954f86c40fa23acf0"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.2/secib_0.0.2_linux_amd64.tar.gz"
      sha256 "f164762c2a692ca00f3fb109069dee9426f15d6c2bd818e2dcbead0b9d33d2ae"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.2/secib_0.0.2_linux_arm64.tar.gz"
      sha256 "ea56aa53a1a364a31e57533f70c792611b20285707b819a483dd85790ac79b48"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  test do
    system "#{bin}/secib", "version"
  end
end
