# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secib < Formula
  desc "CLI for the NPL SECIB gateway + MCP companion"
  homepage "https://github.com/Karugency97/secib-cli"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.4/secib_0.0.4_darwin_amd64.tar.gz"
      sha256 "06a63b31fe7bd698664b112fe582ab174930a9c9e2508d7fe9b954d23b1c20f6"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.4/secib_0.0.4_darwin_arm64.tar.gz"
      sha256 "416a3cf4acd9e6f9e25d995e214809156689ee846578048169348f482da920a9"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.4/secib_0.0.4_linux_amd64.tar.gz"
      sha256 "3c3db3fcb5fb8bd901596e63f8dee4b6f58ce82a68931ab03e1afc48dbf41ed9"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.4/secib_0.0.4_linux_arm64.tar.gz"
      sha256 "1e34968c0f5c4ed093b7e0e33d975a9494ec498b8f2c50de3946b93f38ba2e25"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  test do
    system "#{bin}/secib", "version"
  end
end
