# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secib < Formula
  desc "CLI for the NPL SECIB gateway + MCP companion"
  homepage "https://github.com/Karugency97/secib-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_darwin_amd64.tar.gz"
      sha256 "ad0420b7fcdecf2113359c3577b497927729e137b79f44b5d346aa87d46ae3fb"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_darwin_arm64.tar.gz"
      sha256 "683e7d34f05b4a0cff2206da6ebf71558c623879f41d49d61658ed61cf2d4d05"

      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_linux_amd64.tar.gz"
      sha256 "97930eb2a49d6eb1a5367f5447f18b0cdd7668e7cc1262b9b9c7a43fd55cefcb"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Karugency97/secib-cli/releases/download/v0.0.1/secib_0.0.1_linux_arm64.tar.gz"
      sha256 "b0ce44291a7de8b982353eff83ff9227b9e46afb75954b420eb5f0be82457758"
      define_method(:install) do
        bin.install "secib"
        bin.install "secib-mcp"
      end
    end
  end

  test do
    system "#{bin}/secib", "version"
  end
end
